use core::fmt::Display;

#[derive(Clone)]
pub enum NodeShape {
    Box,
    Ellipse,
    Circle,
    Diamond,
    Plaintext,
    Point,
    Polygon,
    Rect,
    Record,
    Mrecord,
    Square,
    Star,
    None,
    Trapezium,
    Triangle,
    House,
    InvHouse,
    Parallelogram,
    Hexagon,
    Septagon,
    Octagon,
    Doublecircle,
    Doubleoctagon,
    Tripleoctagon,
    Invtriangle,
    Mdiamond,
    Msquare,
    Mcircle,
    Note,
    Tab,
    Folder,
    Box3d,
    Component,
    Promoter,
    Cds,
    Terminator,
    Utr,
    Primersite,
    Restrictionsite,
    Fivepoverhang,
    Threepoverhang,
    Noverhang,
    Assembly,
    Signature,
    Insulator,
    Ribosite,
    Rnastab,
    Proteasesite,
    Proteinstab,
    Rpromoter,
    Larrow,
    Rarrow,
    Lpromoter,
}

impl Display for NodeShape {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let shape = match self {
            Self::Box => "box",
            Self::Ellipse => "ellipse",
            Self::Circle => "circle",
            Self::Diamond => "diamond",
            Self::Plaintext => "plaintext",
            Self::Point => "point",
            Self::Polygon => "polygon",
            Self::Rect => "rect",
            Self::Record => "record",
            Self::Mrecord => "mrecord",
            Self::Square => "square",
            Self::Star => "star",
            Self::None => "none",
            Self::Trapezium => "trapezium",
            Self::Triangle => "triangle",
            Self::House => "house",
            Self::InvHouse => "invhouse",
            Self::Parallelogram => "parallelogram",
            Self::Hexagon => "hexagon",
            Self::Septagon => "septagon",
            Self::Octagon => "octagon",
            Self::Doublecircle => "doublecircle",
            Self::Doubleoctagon => "doubleoctagon",
            Self::Tripleoctagon => "tripleoctagon",
            Self::Invtriangle => "invtriangle",
            Self::Mdiamond => "mdiamond",
            Self::Msquare => "msquare",
            Self::Mcircle => "mcircle",
            Self::Note => "note",
            Self::Tab => "tab",
            Self::Folder => "folder",
            Self::Box3d => "box3d",
            Self::Component => "component",
            Self::Promoter => "promoter",
            Self::Cds => "cds",
            Self::Terminator => "terminator",
            Self::Utr => "utr",
            Self::Primersite => "primersite",
            Self::Restrictionsite => "restrictionsite",
            Self::Fivepoverhang => "fivepoverhang",
            Self::Threepoverhang => "threepoverhang",
            Self::Noverhang => "noverhang",
            Self::Assembly => "assembly",
            Self::Signature => "signature",
            Self::Insulator => "insulator",
            Self::Ribosite => "ribosite",
            Self::Rnastab => "rnastab",
            Self::Proteasesite => "proteasesite",
            Self::Proteinstab => "proteinstab",
            Self::Rpromoter => "rpromoter",
            Self::Larrow => "larrow",
            Self::Rarrow => "rarrow",
            Self::Lpromoter => "lpromoter",
        };

        f.write_str(shape)
    }
}
